### PR TITLE
fix: only show 'powershell' binding on windows

### LINKED ISSUE #18: Powershell: Can't get the correct profile path
**Describe the bug**
Try to run `inshellisense bind` in powershell on macOS and got following error:
```
$ inshellisense bind
Select your desired shell for keybinding creation
  bash
  zsh
  fish
> powershell
  pwsh
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/Users/username/Documents/WindowsPowershell/Microsoft.PowerShell_profile.ps1'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/username/Documents/WindowsPowershell/Microsoft.PowerShell_profile.ps1'
}
```
**To Reproduce**
1. Open powershell  on macOS
2. Run `inshellisense bind`

**Expected behavior**
The correct profile path is `~/.config/powershell/Microsoft.PowerShell_profile.ps1`
```
$ file $PROFILE                                                  
/Users/user/.config/powershell/Microsoft.PowerShell_profile.ps1: ASCII text
```

**Environment**
 - OS: macOS
 - Output of `inshellisense --version`: 0.0.1-rc.1
 - Nodejs Version: 21.1.0

**Additional context**

### PR DESCRIPTION
**Pull request by cpendery**
## Description
In order to avoid confusion between `powershell` and `pwsh` on MacOS/Linux, remove it as a binding option on those OS's

## Testing
- [x] once unbound, powershell is never presented as an option in WSL
- [x] powershell is still presented as an option in Windows

Closes #18

### CODE REVIEW

File: src/utils/bindings.ts [hunk 1]
```diff
@@ -93,13 +95,15 @@ export const availableBindings = async (): Promise<Shell[]> => {
     }
   }
 
-  const powershellConfigPath = path.join(os.homedir(), "Documents", "WindowsPowershell", "Microsoft.PowerShell_profile.ps1");
-  if (!fs.existsSync(powershellConfigPath)) {
-    bindings.push(Shell.Powershell);
-  } else {
-    const powershellConfigContent = fsAsync.readFile(powershellConfigPath, { encoding: "utf-8" });
-    if (!(await powershellConfigContent).includes(powershellScriptCommand())) {
+  if (process.platform == "win32") {
```
Comment (Delta456) [inline src/utils/bindings.ts:98]: I think an explicit error should be there if anyone tries to use `powershell` on non-Windows systems.
